/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import model.Service;
import models.dao.DaoFactory;
import models.dao.ServiceDao;

/**
 *
 * @author Vitor Manoel
 */
public class AlterService extends javax.swing.JFrame {

    ServiceDao serviceDao = DaoFactory.createServiceDao();
    Service service = new Service();
    /**
     * Creates new form AlterService
     */
    public AlterService() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("empresa?serverTimezone=UTCPU").createEntityManager();
        serviceQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Service s");
        serviceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : serviceQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input_id = new javax.swing.JTextField();
        input_name = new javax.swing.JTextField();
        procurar1 = new javax.swing.JButton();
        alter_prod = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        register_serv_button = new javax.swing.JButton();
        delete_serv_button = new javax.swing.JButton();
        list_serv_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 20));

        jSeparator4.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator4.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 20));

        jSeparator5.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator5.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 155, 52));
        jLabel5.setText("Preço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 60, 30));

        preco.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        preco.setForeground(new java.awt.Color(209, 155, 52));
        preco.setBorder(null);
        preco.setCaretColor(new java.awt.Color(209, 155, 52));
        preco.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        preco.setInheritsPopupMenu(true);
        preco.setMargin(new java.awt.Insets(2, 60, 2, 2));
        preco.setName(""); // NOI18N
        preco.setSelectionColor(new java.awt.Color(255, 255, 255));
        preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoActionPerformed(evt);
            }
        });
        jPanel1.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 155, 52));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ALTERAR DADOS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 155, 52));
        jLabel3.setText("SERVIÇO ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 155, 52));
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 60, 30));

        input_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_id.setForeground(new java.awt.Color(209, 155, 52));
        input_id.setBorder(null);
        input_id.setCaretColor(new java.awt.Color(209, 155, 52));
        input_id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_id.setInheritsPopupMenu(true);
        input_id.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_id.setName(""); // NOI18N
        input_id.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });
        jPanel1.add(input_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, 30));

        input_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_name.setForeground(new java.awt.Color(209, 155, 52));
        input_name.setBorder(null);
        input_name.setCaretColor(new java.awt.Color(209, 155, 52));
        input_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_name.setInheritsPopupMenu(true);
        input_name.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_name.setName(""); // NOI18N
        input_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        jPanel1.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 220, 30));

        procurar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottonm-pesquisar.png"))); // NOI18N
        procurar1.setBorderPainted(false);
        procurar1.setContentAreaFilled(false);
        procurar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        procurar1.setFocusPainted(false);
        procurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurar1ActionPerformed(evt);
            }
        });
        jPanel1.add(procurar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, 40));

        alter_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_prod.setBorderPainted(false);
        alter_prod.setContentAreaFilled(false);
        alter_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_prod.setFocusPainted(false);
        alter_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_prodActionPerformed(evt);
            }
        });
        jPanel1.add(alter_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 120, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        register_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        register_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_serv_button.setBorder(null);
        register_serv_button.setBorderPainted(false);
        register_serv_button.setContentAreaFilled(false);
        register_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_serv_button.setFocusPainted(false);
        register_serv_button.setFocusable(false);
        register_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_serv_buttonMouseEntered(evt);
            }
        });
        register_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 40));

        delete_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_serv_button.setBorder(null);
        delete_serv_button.setBorderPainted(false);
        delete_serv_button.setContentAreaFilled(false);
        delete_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_serv_button.setFocusPainted(false);
        delete_serv_button.setFocusable(false);
        delete_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_serv_buttonMouseEntered(evt);
            }
        });
        delete_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(delete_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, 40));

        list_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        list_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_serv_button.setBorder(null);
        list_serv_button.setBorderPainted(false);
        list_serv_button.setContentAreaFilled(false);
        list_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_serv_button.setFocusPainted(false);
        list_serv_button.setFocusable(false);
        list_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_serv_buttonMouseEntered(evt);
            }
        });
        jPanel1.add(list_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 120, 40));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, serviceList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${servicePK.id}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 40, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_idActionPerformed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void procurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurar1ActionPerformed
        try{
            service = serviceDao.findById(Integer.parseInt(input_id.getText()));
            
            JOptionPane.showMessageDialog(null, "Serviço: "+service.getName()+" | Hora: "+service.getHour()+" | Preço: "+service.getPrice());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nenhum serviço foi alterado.", "ERRO", 0);
        }
    }//GEN-LAST:event_procurar1ActionPerformed

    private void alter_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_prodActionPerformed
        try{
            service.setName(input_name.getText());
            service.setPrice(Float.parseFloat(preco.getText()));

            serviceDao.update(service);
            JOptionPane.showMessageDialog(null, "Serviço alterado!", "", 1);
            
            input_name.setText("");
            preco.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nenhuma alteração realizada.", "ERRO", 0);
        }
    }//GEN-LAST:event_alter_prodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoActionPerformed

    private void register_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_serv_buttonMouseEntered

    private void register_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_serv_buttonActionPerformed
        dispose();

        RegisterService register = new RegisterService();
        register.setVisible(true);
    }//GEN-LAST:event_register_serv_buttonActionPerformed

    private void delete_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_serv_buttonMouseEntered

    private void delete_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_serv_buttonActionPerformed
        dispose();

        DeleteService register = new DeleteService();
        register.setVisible(true);
    }//GEN-LAST:event_delete_serv_buttonActionPerformed

    private void list_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_serv_buttonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_prod;
    private javax.swing.JButton delete_serv_button;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_name;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton list_serv_button;
    private javax.swing.JTextField preco;
    private javax.swing.JButton procurar1;
    private javax.swing.JButton register_serv_button;
    private java.util.List<application.Service> serviceList;
    private javax.persistence.Query serviceQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
