/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import model.Animal;
import model.Client;
import models.dao.AnimalDao;
import models.dao.ClientDao;
import models.dao.DaoFactory;

/**
 *
 * @author Vitor Manoel
 */
public class AlterAnimal extends javax.swing.JFrame {
    
    Animal animal = new Animal();
    Client client = new Client();
    AnimalDao animalDao = DaoFactory.createAnimalDao();
    /**
     * Creates new form AlterAnimal
     */
    public AlterAnimal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("empresa?serverTimezone=UTCPU").createEntityManager();
        animalQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Animal a");
        animalList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : animalQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        id_on = new javax.swing.JTextField();
        dono_on = new javax.swing.JTextField();
        especie_on = new javax.swing.JTextField();
        nome_on = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        especie = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        dono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        input_id = new javax.swing.JTextField();
        procurar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        register_pet_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        list_pet_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_on.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_on.setForeground(new java.awt.Color(209, 155, 52));
        id_on.setBorder(null);
        id_on.setMargin(new java.awt.Insets(2, 1, 2, 20));
        jPanel1.add(id_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 180, 30));

        dono_on.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dono_on.setForeground(new java.awt.Color(209, 155, 52));
        dono_on.setBorder(null);
        jPanel1.add(dono_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 180, 30));

        especie_on.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        especie_on.setForeground(new java.awt.Color(209, 155, 52));
        especie_on.setBorder(null);
        jPanel1.add(especie_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 180, 30));

        nome_on.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome_on.setForeground(new java.awt.Color(209, 155, 52));
        nome_on.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome_on.setBorder(null);
        jPanel1.add(nome_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FUNDO-ROSA.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 220, 290));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 155, 52));
        jLabel5.setText("Espécie:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, 30));

        especie.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        especie.setForeground(new java.awt.Color(209, 155, 52));
        especie.setBorder(null);
        especie.setCaretColor(new java.awt.Color(209, 155, 52));
        especie.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        especie.setInheritsPopupMenu(true);
        especie.setName(""); // NOI18N
        especie.setSelectionColor(new java.awt.Color(255, 255, 255));
        especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieActionPerformed(evt);
            }
        });
        jPanel1.add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 210, 30));

        jSeparator4.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator4.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 155, 52));
        jLabel4.setText("Dono (CPF):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 30));

        dono.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dono.setForeground(new java.awt.Color(209, 155, 52));
        dono.setBorder(null);
        dono.setCaretColor(new java.awt.Color(209, 155, 52));
        dono.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dono.setInheritsPopupMenu(true);
        dono.setName(""); // NOI18N
        dono.setSelectionColor(new java.awt.Color(255, 255, 255));
        dono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donoActionPerformed(evt);
            }
        });
        jPanel1.add(dono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 180, 30));

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 280, 20));

        jSeparator1.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator1.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 280, 20));

        jSeparator2.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator2.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 280, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 155, 52));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ALTERAR DADOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 290, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("ID PET:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 30));

        input_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_id.setForeground(new java.awt.Color(209, 155, 52));
        input_id.setBorder(null);
        input_id.setCaretColor(new java.awt.Color(209, 155, 52));
        input_id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_id.setInheritsPopupMenu(true);
        input_id.setName(""); // NOI18N
        input_id.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });
        jPanel1.add(input_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 210, 30));

        procurar.setBorderPainted(false);
        procurar.setContentAreaFilled(false);
        procurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        procurar.setFocusPainted(false);
        procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarActionPerformed(evt);
            }
        });
        jPanel1.add(procurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 290, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 155, 52));
        jLabel2.setText("Novo nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 30));

        nome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nome.setForeground(new java.awt.Color(209, 155, 52));
        nome.setBorder(null);
        nome.setCaretColor(new java.awt.Color(209, 155, 52));
        nome.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nome.setInheritsPopupMenu(true);
        nome.setName(""); // NOI18N
        nome.setSelectionColor(new java.awt.Color(255, 255, 255));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 180, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottonm-pesquisar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 120, 40));

        register_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        register_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_pet_button.setBorder(null);
        register_pet_button.setBorderPainted(false);
        register_pet_button.setContentAreaFilled(false);
        register_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_pet_button.setFocusPainted(false);
        register_pet_button.setFocusable(false);
        register_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_pet_buttonMouseEntered(evt);
            }
        });
        register_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_pet_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        list_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        list_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_pet_button.setBorder(null);
        list_pet_button.setBorderPainted(false);
        list_pet_button.setContentAreaFilled(false);
        list_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_pet_button.setFocusPainted(false);
        list_pet_button.setFocusable(false);
        list_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_pet_buttonMouseEntered(evt);
            }
        });
        list_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_pet_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(list_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed
        
    }//GEN-LAST:event_input_idActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        
        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        animal = animalDao.findById(Integer.parseInt(input_id.getText()));
        ClientDao clientDao = DaoFactory.createClientDao();
        
        nome_on.setText(animal.getName());
        id_on.setText(Integer.toString(animal.getId()));
        especie_on.setText(animal.getSpecies());
        
        client = clientDao.findById(animal.getOwner());
        
        dono_on.setText(client.getName());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarActionPerformed
        animal = animalDao.findById(Integer.parseInt(input_id.getText()));
        System.out.println(animal);
        System.out.println(animal.getName());
    }//GEN-LAST:event_procurarActionPerformed

    private void donoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donoActionPerformed

    private void especieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            animal.setName(nome.getText());
            animal.setSpecies(especie.getText());
            animal.setOwner(Integer.parseInt(dono.getText()));
            animalDao.update(animal);
            
            JOptionPane.showMessageDialog(null, "Dados atualizados!", "", 1);
            
            input_id.setText("");
            nome.setText("");
            especie.setText("");
            dono.setText("");
            
            nome_on.setText("");
            especie_on.setText("");
            id_on.setText("");
            dono_on.setText("");
            
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Não foi possivel atualizar.", "ERRO", 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void register_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_pet_buttonMouseEntered

    private void register_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_pet_buttonActionPerformed
        dispose();

        RegisterAnimal register = new RegisterAnimal();
        register.setVisible(true);
    }//GEN-LAST:event_register_pet_buttonActionPerformed

    private void list_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_pet_buttonMouseEntered

    private void list_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_pet_buttonActionPerformed
        dispose();

        ListAnimals list = new ListAnimals();
        list.setVisible(true);
    }//GEN-LAST:event_list_pet_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AlterAnimal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<application.Animal> animalList;
    private javax.persistence.Query animalQuery;
    private javax.swing.JTextField dono;
    private javax.swing.JTextField dono_on;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField especie;
    private javax.swing.JTextField especie_on;
    private javax.swing.JTextField id_on;
    private javax.swing.JTextField input_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton list_pet_button;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nome_on;
    private javax.swing.JButton procurar;
    private javax.swing.JButton register_pet_button;
    // End of variables declaration//GEN-END:variables
}
