/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import model.Products;
import models.dao.DaoFactory;
import models.dao.ProductsDao;

/**
 *
 * @author Vitor Manoel
 */
public class DeleteProduct extends javax.swing.JFrame {
    
    Products product = new Products();
    ProductsDao productsDao = DaoFactory.createProductDao();
    /**
     * Creates new form DeleteProduct
     */
    public DeleteProduct() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        alter_prod_button = new javax.swing.JButton();
        list_prod_button = new javax.swing.JButton();
        register_prod_button = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator1.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 280, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 155, 52));
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, 30));

        input_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_name.setForeground(new java.awt.Color(209, 155, 52));
        input_name.setBorder(null);
        input_name.setCaretColor(new java.awt.Color(209, 155, 52));
        input_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_name.setInheritsPopupMenu(true);
        input_name.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_name.setName(""); // NOI18N
        input_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        jPanel1.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, 30));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setFocusPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 155, 52));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EXCLUIR PRODUTO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, -1));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 330, -1));

        alter_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_prod_button.setBorder(null);
        alter_prod_button.setBorderPainted(false);
        alter_prod_button.setContentAreaFilled(false);
        alter_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_prod_button.setFocusPainted(false);
        alter_prod_button.setFocusable(false);
        alter_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_prod_buttonMouseEntered(evt);
            }
        });
        alter_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, 40));

        list_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        list_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_prod_button.setBorder(null);
        list_prod_button.setBorderPainted(false);
        list_prod_button.setContentAreaFilled(false);
        list_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_prod_button.setFocusPainted(false);
        list_prod_button.setFocusable(false);
        list_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_prod_buttonMouseEntered(evt);
            }
        });
        list_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(list_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 40));

        register_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        register_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_prod_button.setBorder(null);
        register_prod_button.setBorderPainted(false);
        register_prod_button.setContentAreaFilled(false);
        register_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_prod_button.setFocusPainted(false);
        register_prod_button.setFocusable(false);
        register_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_prod_buttonMouseEntered(evt);
            }
        });
        register_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 120, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton10.setToolTipText("");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
            productsDao.deleteByName(input_name.getText());
        
            JOptionPane.showMessageDialog(null, "Apagado com sucesso!", "", 1);
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Nenhum produto apagado.", "ERRP", 0);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void alter_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_prod_buttonMouseEntered

    private void alter_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_prod_buttonActionPerformed
        dispose();

        AlterProducts register = new AlterProducts();
        register.setVisible(true);
    }//GEN-LAST:event_alter_prod_buttonActionPerformed

    private void list_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_prod_buttonMouseEntered

    private void register_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_prod_buttonMouseEntered

    private void register_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_prod_buttonActionPerformed
        dispose();

        RegisterProd register = new RegisterProd();
        register.setVisible(true);
    }//GEN-LAST:event_register_prod_buttonActionPerformed

    private void jButton10jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton10jButton2ActionPerformed

    private void list_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_prod_buttonActionPerformed
        dispose();
        
        ListProducts pro = new ListProducts();
        pro.setVisible(true);
    }//GEN-LAST:event_list_prod_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_prod_button;
    private javax.swing.JButton delete;
    private javax.swing.JTextField input_name;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton list_prod_button;
    private javax.swing.JButton register_prod_button;
    // End of variables declaration//GEN-END:variables
}
