/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import model.Products;
import models.dao.AppointmentDao;
import models.dao.DaoFactory;
import models.dao.ProductsDao;

/**
 *
 * @author Vitor Manoel
 */
public class EmployeeScreen extends javax.swing.JFrame {

    /**
     * Creates new form TelaClinica
     */
    public EmployeeScreen() {
        initComponents();
        setLocationRelativeTo(null);
        func_register_button.setVisible(false);
        register_pet_button.setVisible(false);
        alter_pet_button.setVisible(false);
        list_pet_button.setVisible(false);
        register_prod_button.setVisible(false);
        alter_prod_button.setVisible(false);
        delete_prod_button.setVisible(false);
        list_prod_button.setVisible(false);
        register_serv_button.setVisible(false);
        alter_serv_button.setVisible(false);
        delete_serv_button.setVisible(false);
        list_serv_button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        list_pet_button = new javax.swing.JButton();
        alter_pet_button = new javax.swing.JButton();
        register_pet_button = new javax.swing.JButton();
        func_register_button = new javax.swing.JButton();
        pets_button = new javax.swing.JButton();
        consultas_button = new javax.swing.JButton();
        register_serv_button = new javax.swing.JButton();
        alter_serv_button = new javax.swing.JButton();
        list_serv_button = new javax.swing.JButton();
        delete_serv_button = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        products_button = new javax.swing.JButton();
        register_prod_button = new javax.swing.JButton();
        alter_prod_button = new javax.swing.JButton();
        delete_prod_button = new javax.swing.JButton();
        list_prod_button = new javax.swing.JButton();
        sep_hor = new javax.swing.JSeparator();
        sep_vert = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_button.setBackground(new java.awt.Color(254, 232, 231));
        register_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_button.setBorder(null);
        register_button.setBorderPainted(false);
        register_button.setContentAreaFilled(false);
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.setFocusPainted(false);
        register_button.setFocusable(false);
        register_button.setMaximumSize(new java.awt.Dimension(104, 22));
        register_button.setMinimumSize(new java.awt.Dimension(104, 22));
        register_button.setPreferredSize(new java.awt.Dimension(104, 22));
        register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_buttonMouseExited(evt);
            }
        });
        jPanel2.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 40));

        list_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        list_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_pet_button.setBorder(null);
        list_pet_button.setBorderPainted(false);
        list_pet_button.setContentAreaFilled(false);
        list_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_pet_button.setFocusPainted(false);
        list_pet_button.setFocusable(false);
        list_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_pet_buttonMouseEntered(evt);
            }
        });
        list_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_pet_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(list_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 40));

        alter_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_pet_button.setBorder(null);
        alter_pet_button.setBorderPainted(false);
        alter_pet_button.setContentAreaFilled(false);
        alter_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_pet_button.setFocusPainted(false);
        alter_pet_button.setFocusable(false);
        alter_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_pet_buttonMouseEntered(evt);
            }
        });
        alter_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_pet_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(alter_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, 40));

        register_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        register_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_pet_button.setBorder(null);
        register_pet_button.setBorderPainted(false);
        register_pet_button.setContentAreaFilled(false);
        register_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_pet_button.setFocusPainted(false);
        register_pet_button.setFocusable(false);
        register_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_pet_buttonMouseEntered(evt);
            }
        });
        register_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_pet_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(register_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 40));

        func_register_button.setBackground(new java.awt.Color(254, 232, 231));
        func_register_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottons.png"))); // NOI18N
        func_register_button.setBorder(null);
        func_register_button.setBorderPainted(false);
        func_register_button.setContentAreaFilled(false);
        func_register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        func_register_button.setFocusPainted(false);
        func_register_button.setFocusable(false);
        func_register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                func_register_buttonMouseEntered(evt);
            }
        });
        func_register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func_register_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(func_register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 40));

        pets_button.setBackground(new java.awt.Color(254, 232, 231));
        pets_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-pets.png"))); // NOI18N
        pets_button.setBorder(null);
        pets_button.setBorderPainted(false);
        pets_button.setContentAreaFilled(false);
        pets_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pets_button.setFocusPainted(false);
        pets_button.setFocusable(false);
        pets_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pets_buttonMouseEntered(evt);
            }
        });
        jPanel2.add(pets_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 40));

        consultas_button.setBackground(new java.awt.Color(254, 232, 231));
        consultas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-consultas.png"))); // NOI18N
        consultas_button.setBorder(null);
        consultas_button.setBorderPainted(false);
        consultas_button.setContentAreaFilled(false);
        consultas_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultas_button.setFocusPainted(false);
        consultas_button.setFocusable(false);
        consultas_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultas_buttonMouseEntered(evt);
            }
        });
        consultas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultas_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(consultas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, 40));

        register_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        register_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_serv_button.setBorder(null);
        register_serv_button.setBorderPainted(false);
        register_serv_button.setContentAreaFilled(false);
        register_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_serv_button.setFocusPainted(false);
        register_serv_button.setFocusable(false);
        register_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_serv_buttonMouseEntered(evt);
            }
        });
        register_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_serv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(register_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 120, 40));

        alter_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_serv_button.setBorder(null);
        alter_serv_button.setBorderPainted(false);
        alter_serv_button.setContentAreaFilled(false);
        alter_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_serv_button.setFocusPainted(false);
        alter_serv_button.setFocusable(false);
        alter_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_serv_buttonMouseEntered(evt);
            }
        });
        alter_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_serv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(alter_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 120, 40));

        list_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        list_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_serv_button.setBorder(null);
        list_serv_button.setBorderPainted(false);
        list_serv_button.setContentAreaFilled(false);
        list_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_serv_button.setFocusPainted(false);
        list_serv_button.setFocusable(false);
        list_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_serv_buttonMouseEntered(evt);
            }
        });
        list_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_serv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(list_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 120, 40));

        delete_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_serv_button.setBorder(null);
        delete_serv_button.setBorderPainted(false);
        delete_serv_button.setContentAreaFilled(false);
        delete_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_serv_button.setFocusPainted(false);
        delete_serv_button.setFocusable(false);
        delete_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_serv_buttonMouseEntered(evt);
            }
        });
        delete_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_serv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(delete_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 120, 40));

        jButton6.setBackground(new java.awt.Color(254, 232, 231));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-serviços.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 120, 40));

        jButton7.setBackground(new java.awt.Color(254, 232, 231));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-sair.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 120, 40));

        products_button.setBackground(new java.awt.Color(254, 232, 231));
        products_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-produtos.png"))); // NOI18N
        products_button.setBorder(null);
        products_button.setBorderPainted(false);
        products_button.setContentAreaFilled(false);
        products_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        products_button.setFocusPainted(false);
        products_button.setFocusable(false);
        products_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                products_buttonMouseEntered(evt);
            }
        });
        jPanel2.add(products_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, 40));

        register_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        register_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_prod_button.setBorder(null);
        register_prod_button.setBorderPainted(false);
        register_prod_button.setContentAreaFilled(false);
        register_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_prod_button.setFocusPainted(false);
        register_prod_button.setFocusable(false);
        register_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_prod_buttonMouseEntered(evt);
            }
        });
        register_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_prod_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(register_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 120, 40));

        alter_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_prod_button.setBorder(null);
        alter_prod_button.setBorderPainted(false);
        alter_prod_button.setContentAreaFilled(false);
        alter_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_prod_button.setFocusPainted(false);
        alter_prod_button.setFocusable(false);
        alter_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_prod_buttonMouseEntered(evt);
            }
        });
        alter_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_prod_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(alter_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 120, 40));

        delete_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_prod_button.setBorder(null);
        delete_prod_button.setBorderPainted(false);
        delete_prod_button.setContentAreaFilled(false);
        delete_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_prod_button.setFocusPainted(false);
        delete_prod_button.setFocusable(false);
        delete_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_prod_buttonMouseEntered(evt);
            }
        });
        delete_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_prod_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(delete_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 120, 40));

        list_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        list_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_prod_button.setBorder(null);
        list_prod_button.setBorderPainted(false);
        list_prod_button.setContentAreaFilled(false);
        list_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_prod_button.setFocusPainted(false);
        list_prod_button.setFocusable(false);
        list_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_prod_buttonMouseEntered(evt);
            }
        });
        list_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_prod_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(list_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 120, 40));

        sep_hor.setBackground(new java.awt.Color(209, 155, 52));
        sep_hor.setForeground(new java.awt.Color(209, 155, 52));
        jPanel2.add(sep_hor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 540, 20));

        sep_vert.setBackground(new java.awt.Color(209, 155, 52));
        sep_vert.setForeground(new java.awt.Color(209, 155, 52));
        sep_vert.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(sep_vert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 20, 350));

        jButton1.setText("NEW");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 190, 140));

        jButton2.setText("NEW");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 190, 140));

        jButton3.setText("CONSULTAS");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 190, 140));

        jButton4.setText("ESTOQUE");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 190, 210));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();

        InitialScreen init = new InitialScreen();
        init.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void register_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseEntered
        func_register_button.setVisible(true);
        
        register_pet_button.setVisible(false);
        alter_pet_button.setVisible(false);
        list_pet_button.setVisible(false);
        
        register_prod_button.setVisible(false);
        alter_prod_button.setVisible(false);
        delete_prod_button.setVisible(false);
        list_prod_button.setVisible(false);
        
        register_serv_button.setVisible(false);
        alter_serv_button.setVisible(false);
        delete_serv_button.setVisible(false);
        list_serv_button.setVisible(false);
    }//GEN-LAST:event_register_buttonMouseEntered

    private void func_register_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_func_register_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_func_register_buttonMouseEntered

    private void register_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseExited
       //vet_register_button.setVisible(false);
    }//GEN-LAST:event_register_buttonMouseExited

    private void register_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_pet_buttonMouseEntered

    private void alter_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_pet_buttonMouseEntered

    private void list_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_pet_buttonMouseEntered

    private void pets_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pets_buttonMouseEntered
        func_register_button.setVisible(false);
        
        register_pet_button.setVisible(true);
        alter_pet_button.setVisible(true);
        list_pet_button.setVisible(true);
       
        register_prod_button.setVisible(false);
        alter_prod_button.setVisible(false);
        delete_prod_button.setVisible(false);
        list_prod_button.setVisible(false);
        
        register_serv_button.setVisible(false);
        alter_serv_button.setVisible(false);
        delete_serv_button.setVisible(false);
        list_serv_button.setVisible(false);
    }//GEN-LAST:event_pets_buttonMouseEntered

    private void consultas_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultas_buttonMouseEntered
        func_register_button.setVisible(false);
        
        register_pet_button.setVisible(false);
        alter_pet_button.setVisible(false);
        list_pet_button.setVisible(false);
        
        register_prod_button.setVisible(false);
        alter_prod_button.setVisible(false);
        delete_prod_button.setVisible(false);
        list_prod_button.setVisible(false);
        
        register_serv_button.setVisible(false);
        alter_serv_button.setVisible(false);
        delete_serv_button.setVisible(false);
        list_serv_button.setVisible(false);
    }//GEN-LAST:event_consultas_buttonMouseEntered

    private void register_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_prod_buttonMouseEntered

    private void alter_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_prod_buttonMouseEntered

    private void delete_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_prod_buttonMouseEntered

    private void list_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_prod_buttonMouseEntered

    private void products_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_buttonMouseEntered
        func_register_button.setVisible(false);
        
        register_pet_button.setVisible(false);
        alter_pet_button.setVisible(false);
        list_pet_button.setVisible(false);
        
        register_prod_button.setVisible(true);
        alter_prod_button.setVisible(true);
        delete_prod_button.setVisible(true);
        list_prod_button.setVisible(true);
        
        register_serv_button.setVisible(false);
        alter_serv_button.setVisible(false);
        delete_serv_button.setVisible(false);
        list_serv_button.setVisible(false);
    }//GEN-LAST:event_products_buttonMouseEntered

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        func_register_button.setVisible(false);
        
        register_pet_button.setVisible(false);
        alter_pet_button.setVisible(false);
        list_pet_button.setVisible(false);
        
        register_prod_button.setVisible(false);
        alter_prod_button.setVisible(false);
        delete_prod_button.setVisible(false);
        list_prod_button.setVisible(false);
        
        register_serv_button.setVisible(false);
        alter_serv_button.setVisible(false);
        delete_serv_button.setVisible(false);
        list_serv_button.setVisible(false);
    }//GEN-LAST:event_jButton7MouseEntered

    private void register_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_serv_buttonMouseEntered

    private void alter_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_serv_buttonMouseEntered

    private void delete_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_serv_buttonMouseEntered

    private void list_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_serv_buttonMouseEntered

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        func_register_button.setVisible(false);
        
        register_pet_button.setVisible(false);
        alter_pet_button.setVisible(false);
        list_pet_button.setVisible(false);
        
        register_prod_button.setVisible(false);
        alter_prod_button.setVisible(false);
        delete_prod_button.setVisible(false);
        list_prod_button.setVisible(false);
        
        register_serv_button.setVisible(true);
        alter_serv_button.setVisible(true);
        delete_serv_button.setVisible(true);
        list_serv_button.setVisible(true);
    }//GEN-LAST:event_jButton6MouseEntered

    private void consultas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultas_buttonActionPerformed
        dispose();
        
        AppointmentScreen ap = new AppointmentScreen();
        ap.setVisible(true);
    }//GEN-LAST:event_consultas_buttonActionPerformed

    private void func_register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func_register_buttonActionPerformed
        dispose();
        
        RegisterFunc register = new RegisterFunc();
        register.setVisible(true);
    }//GEN-LAST:event_func_register_buttonActionPerformed

    private void register_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_pet_buttonActionPerformed
        dispose();
        
        RegisterAnimal register = new RegisterAnimal();
        register.setVisible(true);
    }//GEN-LAST:event_register_pet_buttonActionPerformed

    private void alter_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_pet_buttonActionPerformed
        dispose();
        
        AlterAnimal alter = new AlterAnimal();
        alter.setVisible(true);
    }//GEN-LAST:event_alter_pet_buttonActionPerformed

    private void list_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_pet_buttonActionPerformed
        dispose();
        
        ListAnimals list = new ListAnimals();
        list.setVisible(true);
    }//GEN-LAST:event_list_pet_buttonActionPerformed

    private void register_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_prod_buttonActionPerformed
          dispose();
          
          RegisterProd register = new RegisterProd();
          register.setVisible(true);
    }//GEN-LAST:event_register_prod_buttonActionPerformed

    private void alter_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_prod_buttonActionPerformed
        dispose();
          
        AlterProducts register = new AlterProducts();
        register.setVisible(true);
    }//GEN-LAST:event_alter_prod_buttonActionPerformed

    private void delete_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_prod_buttonActionPerformed
        dispose();
          
        DeleteProduct register = new DeleteProduct();
        register.setVisible(true);
    }//GEN-LAST:event_delete_prod_buttonActionPerformed

    private void register_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_serv_buttonActionPerformed
        dispose();
          
        RegisterService register = new RegisterService();
        register.setVisible(true);
    }//GEN-LAST:event_register_serv_buttonActionPerformed

    private void alter_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_serv_buttonActionPerformed
        dispose();
          
        AlterService register = new AlterService();
        register.setVisible(true);
    }//GEN-LAST:event_alter_serv_buttonActionPerformed

    private void delete_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_serv_buttonActionPerformed
        dispose();
          
        DeleteService register = new DeleteService();
        register.setVisible(true);
    }//GEN-LAST:event_delete_serv_buttonActionPerformed

    private void list_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_prod_buttonActionPerformed
        dispose();
        
        ListProducts pro = new ListProducts();
        pro.setVisible(true);
    }//GEN-LAST:event_list_prod_buttonActionPerformed

    private void list_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_serv_buttonActionPerformed
        dispose();
        
        ListService ser = new ListService();
        ser.setVisible(true);
    }//GEN-LAST:event_list_serv_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LocalDate hoje = LocalDate.now();
        
        AppointmentDao appointmentDao = DaoFactory.createAppointmentDao();
        
        List<model.Appointment> list = appointmentDao.findAll();

            list.forEach((obj) -> {
                
            String data = obj.getDate();
            
            if(hoje.toString().equals(data)){
                JOptionPane.showMessageDialog(null, "Consulta marcada para as "+obj.getHour(), "CONSULTA", 1);
            }
            
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ProductsDao productsDao = DaoFactory.createProductDao(); 
        List<Products> list = productsDao.findAll();
        list.forEach((obj) -> {
            if(obj.getamount() < 10){
                JOptionPane.showMessageDialog(null, "Precisa fazer novos pedidos de "+obj.getName()+" | Quantidade atual: "+obj.getamount(), "INFO", 1);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmployeeScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_pet_button;
    private javax.swing.JButton alter_prod_button;
    private javax.swing.JButton alter_serv_button;
    private javax.swing.JButton consultas_button;
    private javax.swing.JButton delete_prod_button;
    private javax.swing.JButton delete_serv_button;
    private javax.swing.JButton func_register_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton list_pet_button;
    private javax.swing.JButton list_prod_button;
    private javax.swing.JButton list_serv_button;
    private javax.swing.JButton pets_button;
    private javax.swing.JButton products_button;
    private javax.swing.JButton register_button;
    private javax.swing.JButton register_pet_button;
    private javax.swing.JButton register_prod_button;
    private javax.swing.JButton register_serv_button;
    private javax.swing.JSeparator sep_hor;
    private javax.swing.JSeparator sep_vert;
    // End of variables declaration//GEN-END:variables
}
