/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.util.List;
import javax.swing.JOptionPane;
import model.Products;
import models.dao.DaoFactory;
import models.dao.ProductsDao;

/**
 *
 * @author Vitor Manoel
 */
public class ListProducts extends javax.swing.JFrame {

    ProductsDao productsDao = DaoFactory.createProductDao();
    Products product = new Products();
    /**
     * Creates new form ListProducts
     */
    public ListProducts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("empresa?serverTimezone=UTCPU").createEntityManager();
        animalQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Animal a");
        animalList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : animalQuery.getResultList();
        productQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Product p");
        productList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        alter_prod_button = new javax.swing.JButton();
        delete_prod_button = new javax.swing.JButton();
        register_prod_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton11.setToolTipText("");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 40));

        alter_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_prod_button.setBorder(null);
        alter_prod_button.setBorderPainted(false);
        alter_prod_button.setContentAreaFilled(false);
        alter_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_prod_button.setFocusPainted(false);
        alter_prod_button.setFocusable(false);
        alter_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_prod_buttonMouseEntered(evt);
            }
        });
        alter_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, 40));

        delete_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_prod_button.setBorder(null);
        delete_prod_button.setBorderPainted(false);
        delete_prod_button.setContentAreaFilled(false);
        delete_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_prod_button.setFocusPainted(false);
        delete_prod_button.setFocusable(false);
        delete_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_prod_buttonMouseEntered(evt);
            }
        });
        delete_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(delete_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 40));

        register_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        register_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_prod_button.setBorder(null);
        register_prod_button.setBorderPainted(false);
        register_prod_button.setContentAreaFilled(false);
        register_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_prod_button.setFocusPainted(false);
        register_prod_button.setFocusable(false);
        register_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_prod_buttonMouseEntered(evt);
            }
        });
        register_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 120, 40));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productPK.id}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productPK.name}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${amount}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Preço");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${category}"));
        columnBinding.setColumnName("Categoria");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idClinic}"));
        columnBinding.setColumnName("Clinica");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(80);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 470, 330));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("PESQUISA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        pesquisa.setForeground(new java.awt.Color(209, 155, 52));
        pesquisa.setBorder(null);
        pesquisa.setCaretColor(new java.awt.Color(209, 155, 52));
        jPanel1.add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottonm-pesquisar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 40));

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton11jButton2ActionPerformed

    private void alter_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_prod_buttonMouseEntered

    private void alter_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_prod_buttonActionPerformed
        dispose();

        AlterProducts register = new AlterProducts();
        register.setVisible(true);
    }//GEN-LAST:event_alter_prod_buttonActionPerformed

    private void delete_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_prod_buttonMouseEntered

    private void delete_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_prod_buttonActionPerformed
        dispose();

        DeleteProduct register = new DeleteProduct();
        register.setVisible(true);
    }//GEN-LAST:event_delete_prod_buttonActionPerformed

    private void register_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_prod_buttonMouseEntered

    private void register_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_prod_buttonActionPerformed
        dispose();

        RegisterProd register = new RegisterProd();
        register.setVisible(true);
    }//GEN-LAST:event_register_prod_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
               product = productsDao.findByName(pesquisa.getText());
        
            JOptionPane.showMessageDialog(null, "Nome: "+product.getName()+" | Produto ID: "+product.getId()+" | Quantidade: "+product.getamount());
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"Nenhum item encontrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List<Products> list = productsDao.findAll();

            list.forEach((obj) -> {
                if(obj.getamount() < 10){
                    JOptionPane.showMessageDialog(null, "Precisa fazer novos pedidos de "+obj.getName()+" | Quantidade atual: "+obj.getamount(), "INFO", 1);
                }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_prod_button;
    private java.util.List<application.Animal> animalList;
    private javax.persistence.Query animalQuery;
    private javax.swing.JButton delete_prod_button;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pesquisa;
    private java.util.List<application.Product> productList;
    private javax.persistence.Query productQuery;
    private javax.swing.JButton register_prod_button;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
