/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package application;

import db.DbException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.Client;
import models.dao.ClientDao;
import models.dao.DaoFactory;

/**
 *
 * @author Vitor Manoel
 */
public class ListAnimals extends javax.swing.JFrame {

    Connection conn = null;
    /** Creates new form ListAnimals */
    public ListAnimals() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("empresa?serverTimezone=UTCPU").createEntityManager();
        animalQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT a FROM Animal a");
        animalList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : animalQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        init_button = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        register_pet_button = new javax.swing.JButton();
        alter_pet_button = new javax.swing.JButton();
        nome_cliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tel_cliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ende_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        init_button.setForeground(new java.awt.Color(255, 255, 255));
        init_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        init_button.setBorderPainted(false);
        init_button.setContentAreaFilled(false);
        init_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        init_button.setFocusPainted(false);
        init_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                init_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(init_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 220, 30));

        register_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        register_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_pet_button.setBorder(null);
        register_pet_button.setBorderPainted(false);
        register_pet_button.setContentAreaFilled(false);
        register_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_pet_button.setFocusPainted(false);
        register_pet_button.setFocusable(false);
        register_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_pet_buttonMouseEntered(evt);
            }
        });
        register_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_pet_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, 40));

        alter_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_pet_button.setBorder(null);
        alter_pet_button.setBorderPainted(false);
        alter_pet_button.setContentAreaFilled(false);
        alter_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_pet_button.setFocusPainted(false);
        alter_pet_button.setFocusable(false);
        alter_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_pet_buttonMouseEntered(evt);
            }
        });
        alter_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_pet_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 40));

        nome_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 220, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("DADOS DO CLIENTE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 155, 52));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 357, 50, 30));

        email_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(email_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 155, 52));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 155, 52));
        jLabel4.setText("Tel:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 40, 30));

        tel_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(tel_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 220, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 20, 100));

        ende_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ende_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(ende_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 155, 52));
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 70, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottonm-pesquisar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 155, 52));
        jLabel6.setText("CPF:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, animalList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ownerId}"));
        columnBinding.setColumnName("Dono");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${species}"));
        columnBinding.setColumnName("Espécie");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 480, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_init_buttonActionPerformed
        dispose();

        EmployeeScreen init = new EmployeeScreen();
        init.setVisible(true);
    }//GEN-LAST:event_init_buttonActionPerformed

    private void register_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_pet_buttonMouseEntered

    private void register_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_pet_buttonActionPerformed
        dispose();

        RegisterAnimal register = new RegisterAnimal();
        register.setVisible(true);
    }//GEN-LAST:event_register_pet_buttonActionPerformed

    private void alter_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_pet_buttonMouseEntered

    private void alter_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_pet_buttonActionPerformed
        dispose();

        AlterAnimal alter = new AlterAnimal();
        alter.setVisible(true);
    }//GEN-LAST:event_alter_pet_buttonActionPerformed

    private void nome_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_clienteActionPerformed
        
    }//GEN-LAST:event_nome_clienteActionPerformed

    private void email_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_clienteActionPerformed

    private void tel_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_clienteActionPerformed

    private void ende_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ende_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ende_clienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClientDao clientDao = DaoFactory.createClientDao();
        Client client = new Client();
          
        client = clientDao.findById(Integer.parseInt(id.getText()));
        nome_cliente.setText(client.getName());
        email_cliente.setText(client.getEmail());
        ende_cliente.setText(client.getAdress());
        tel_cliente.setText(Integer.toString(client.getTel()));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListAnimals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_pet_button;
    private java.util.List<application.Animal> animalList;
    private javax.persistence.Query animalQuery;
    private javax.swing.JTextField email_cliente;
    private javax.swing.JTextField ende_cliente;
    private javax.persistence.EntityManager entityManager0;
    private javax.swing.JTextField id;
    private javax.swing.JButton init_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nome_cliente;
    private javax.swing.JButton register_pet_button;
    private javax.swing.JTextField tel_cliente;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
