/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import models.dao.DaoFactory;
import models.dao.ServiceDao;

/**
 *
 * @author Vitor Manoel
 */
public class ListService extends javax.swing.JFrame {

    ServiceDao serviceDao = DaoFactory.createServiceDao();
    model.Service service = new model.Service();
    /**
     * Creates new form ListService
     */
    public ListService() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("empresa?serverTimezone=UTCPU").createEntityManager();
        serviceQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Service s");
        serviceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : serviceQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        register_serv_button = new javax.swing.JButton();
        alter_serv_button = new javax.swing.JButton();
        delete_serv_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pesq = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 40));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, serviceList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${servicePK.id}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${servicePK.name}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Preço");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idClinic}"));
        columnBinding.setColumnName("Clinica");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 470, 310));

        register_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        register_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_serv_button.setBorder(null);
        register_serv_button.setBorderPainted(false);
        register_serv_button.setContentAreaFilled(false);
        register_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_serv_button.setFocusPainted(false);
        register_serv_button.setFocusable(false);
        register_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_serv_buttonMouseEntered(evt);
            }
        });
        register_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 120, 40));

        alter_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_serv_button.setBorder(null);
        alter_serv_button.setBorderPainted(false);
        alter_serv_button.setContentAreaFilled(false);
        alter_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_serv_button.setFocusPainted(false);
        alter_serv_button.setFocusable(false);
        alter_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_serv_buttonMouseEntered(evt);
            }
        });
        alter_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, 40));

        delete_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_serv_button.setBorder(null);
        delete_serv_button.setBorderPainted(false);
        delete_serv_button.setContentAreaFilled(false);
        delete_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_serv_button.setFocusPainted(false);
        delete_serv_button.setFocusable(false);
        delete_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_serv_buttonMouseEntered(evt);
            }
        });
        delete_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(delete_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("PESQUISA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        pesq.setForeground(new java.awt.Color(209, 155, 52));
        pesq.setBorder(null);
        pesq.setCaretColor(new java.awt.Color(209, 155, 52));
        jPanel1.add(pesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottonm-pesquisar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void register_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_serv_buttonMouseEntered

    private void register_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_serv_buttonActionPerformed
        dispose();

        RegisterService register = new RegisterService();
        register.setVisible(true);
    }//GEN-LAST:event_register_serv_buttonActionPerformed

    private void alter_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_serv_buttonMouseEntered

    private void alter_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_serv_buttonActionPerformed
        dispose();

        AlterService register = new AlterService();
        register.setVisible(true);
    }//GEN-LAST:event_alter_serv_buttonActionPerformed

    private void delete_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_serv_buttonMouseEntered

    private void delete_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_serv_buttonActionPerformed
        dispose();

        DeleteService register = new DeleteService();
        register.setVisible(true);
    }//GEN-LAST:event_delete_serv_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            service = serviceDao.findByServiceName(pesq.getText());
            
            JOptionPane.showMessageDialog(null, "Nome: "+service.getName()+" | Serviço ID: "+service.getId()+" | Preço atual: "+service.getPrice());
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"Nenhum serviço encontrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_serv_button;
    private javax.swing.JButton delete_serv_button;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pesq;
    private javax.swing.JButton register_serv_button;
    private java.util.List<application.Service> serviceList;
    private javax.persistence.Query serviceQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
