/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import model.Client;
import models.dao.ClientDao;
import models.dao.DaoFactory;

/**
 *
 * @author Vitor Manoel
 */
public class Login extends javax.swing.JFrame{
            
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        button_signin = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        Label_email = new javax.swing.JLabel();
        Label_password = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        button_register = new javax.swing.JToggleButton();
        text_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 330, 10));

        jSeparator1.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator1.setForeground(new java.awt.Color(209, 155, 52));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 330, 10));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-inicio.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, 40));

        button_signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom---login.png"))); // NOI18N
        button_signin.setBorderPainted(false);
        button_signin.setContentAreaFilled(false);
        button_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_signin.setFocusPainted(false);
        button_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signinActionPerformed(evt);
            }
        });
        getContentPane().add(button_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 240, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 480));

        Label_email.setBackground(new java.awt.Color(0, 0, 0));
        Label_email.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Label_email.setForeground(new java.awt.Color(209, 155, 52));
        Label_email.setText("Email:");
        getContentPane().add(Label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 60, 30));

        Label_password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Label_password.setForeground(new java.awt.Color(209, 155, 52));
        Label_password.setText("Senha:");
        getContentPane().add(Label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 60, 30));

        text_password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        text_password.setForeground(new java.awt.Color(209, 155, 52));
        text_password.setBorder(null);
        text_password.setSelectionColor(new java.awt.Color(255, 255, 255));
        text_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("Não possui conta?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 130, 40));

        button_register.setBackground(new java.awt.Color(255, 255, 255));
        button_register.setForeground(new java.awt.Color(255, 255, 255));
        button_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        button_register.setBorderPainted(false);
        button_register.setContentAreaFilled(false);
        button_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_register.setFocusPainted(false);
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });
        getContentPane().add(button_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 130, 40));

        text_email.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        text_email.setForeground(new java.awt.Color(209, 155, 52));
        text_email.setBorder(null);
        text_email.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        text_email.setInheritsPopupMenu(true);
        text_email.setMargin(new java.awt.Insets(2, 60, 2, 2));
        text_email.setName(""); // NOI18N
        text_email.setSelectionColor(new java.awt.Color(255, 255, 255));
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });
        getContentPane().add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 270, 30));
        text_email.getAccessibleContext().setAccessibleName("email");
        text_email.getAccessibleContext().setAccessibleDescription("email");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/roi.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, 250, 210));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FUNDO-ROSA.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 155, 52));
        jLabel2.setText("SEJA BEM VINDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 160, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/branco.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 420, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signinActionPerformed
        ClientDao clientDao = DaoFactory.createClientDao();
        Client client = new Client();
        
        client = clientDao.findByEmail(text_email.getText(), text_password.getText());
        
        try{
           if(text_email.getText().equals(client.getEmail())){
               JOptionPane.showMessageDialog(null, "Logado", "LOGIN", 1);
               
               dispose();
               if(client.getControler() == 3){
                   EmployeeScreen clinica = new EmployeeScreen();
                   clinica.setVisible(true);
               }
               else{
                   ClientScreen clientScreen = new ClientScreen();
                   clientScreen.Data(client);
                   clientScreen.setVisible(true);
               }
         } 
         }catch(NullPointerException ee){
            JOptionPane.showMessageDialog(null, "Email ou senha incorretos", "ERRO", 0);
         }
          
    }//GEN-LAST:event_button_signinActionPerformed

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        dispose();
        
        RegisterClient cad = new RegisterClient();
        cad.setVisible(true);
    }//GEN-LAST:event_button_registerActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        
    }//GEN-LAST:event_text_emailActionPerformed

    private void text_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        
        InitialScreen init = new InitialScreen();
        init.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_email;
    private javax.swing.JLabel Label_password;
    private javax.swing.JLabel background;
    private javax.swing.JToggleButton button_register;
    private javax.swing.JToggleButton button_signin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField text_email;
    private javax.swing.JPasswordField text_password;
    // End of variables declaration//GEN-END:variables

}
