/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import model.Service;
import models.dao.DaoFactory;
import models.dao.ServiceDao;

/**
 *
 * @author Vitor Manoel
 */
public class RegisterService extends javax.swing.JFrame {

    ServiceDao serviceDao = DaoFactory.createServiceDao();
    Service service = new Service();
    /**
     * Creates new form RegisterService
     */
    public RegisterService() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        input_hour = new javax.swing.JTextField();
        input_price = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        register_serv_button = new javax.swing.JButton();
        alter_serv_button = new javax.swing.JButton();
        delete_serv_button = new javax.swing.JButton();
        list_serv_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator1.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 20));

        jSeparator2.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator2.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 280, 20));

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 280, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 155, 52));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CADASTRAR SERVIÇO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 155, 52));
        jLabel2.setText("Preço:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 155, 52));
        jLabel3.setText("Hora:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 50, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, 30));

        input_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_name.setForeground(new java.awt.Color(209, 155, 52));
        input_name.setBorder(null);
        input_name.setCaretColor(new java.awt.Color(209, 155, 52));
        input_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_name.setInheritsPopupMenu(true);
        input_name.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_name.setName(""); // NOI18N
        input_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        jPanel1.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, 30));

        input_hour.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_hour.setForeground(new java.awt.Color(209, 155, 52));
        input_hour.setBorder(null);
        input_hour.setCaretColor(new java.awt.Color(209, 155, 52));
        input_hour.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_hour.setInheritsPopupMenu(true);
        input_hour.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_hour.setName(""); // NOI18N
        input_hour.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_hourActionPerformed(evt);
            }
        });
        jPanel1.add(input_hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 230, 30));

        input_price.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_price.setForeground(new java.awt.Color(209, 155, 52));
        input_price.setBorder(null);
        input_price.setCaretColor(new java.awt.Color(209, 155, 52));
        input_price.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_price.setInheritsPopupMenu(true);
        input_price.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_price.setName(""); // NOI18N
        input_price.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_priceActionPerformed(evt);
            }
        });
        jPanel1.add(input_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        register_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        register_serv_button.setBorderPainted(false);
        register_serv_button.setContentAreaFilled(false);
        register_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_serv_button.setFocusPainted(false);
        register_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_serv_buttonMouseEntered(evt);
            }
        });
        register_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 40));

        alter_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_serv_button.setBorder(null);
        alter_serv_button.setBorderPainted(false);
        alter_serv_button.setContentAreaFilled(false);
        alter_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_serv_button.setFocusPainted(false);
        alter_serv_button.setFocusable(false);
        alter_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_serv_buttonMouseEntered(evt);
            }
        });
        alter_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 40));

        delete_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_serv_button.setBorder(null);
        delete_serv_button.setBorderPainted(false);
        delete_serv_button.setContentAreaFilled(false);
        delete_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_serv_button.setFocusPainted(false);
        delete_serv_button.setFocusable(false);
        delete_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_serv_buttonMouseEntered(evt);
            }
        });
        delete_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(delete_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, 40));

        list_serv_button.setBackground(new java.awt.Color(254, 232, 231));
        list_serv_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_serv_button.setBorder(null);
        list_serv_button.setBorderPainted(false);
        list_serv_button.setContentAreaFilled(false);
        list_serv_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_serv_button.setFocusPainted(false);
        list_serv_button.setFocusable(false);
        list_serv_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_serv_buttonMouseEntered(evt);
            }
        });
        list_serv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_serv_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(list_serv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_hourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_hourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_hourActionPerformed

    private void input_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_priceActionPerformed

    private void register_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register_serv_buttonMouseEntered

    private void register_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_serv_buttonActionPerformed
        try{
            service.setName(input_name.getText());
            service.setPrice(Float.parseFloat(input_price.getText()));
            service.setHour(input_hour.getText());
            service.setIdClinic(999888777);

            serviceDao.insert(service);

            JOptionPane.showMessageDialog(null, "Serviço cadastrado!", "", 1);
            
            input_name.setText("");
            input_price.setText("");
            input_hour.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nenhum serviço foi cadastrado.", "ERRO", 0);
        }
    }//GEN-LAST:event_register_serv_buttonActionPerformed

    private void alter_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_serv_buttonMouseEntered

    private void alter_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_serv_buttonActionPerformed
        dispose();

        AlterService register = new AlterService();
        register.setVisible(true);
    }//GEN-LAST:event_alter_serv_buttonActionPerformed

    private void delete_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_serv_buttonMouseEntered

    private void delete_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_serv_buttonActionPerformed
        dispose();

        DeleteService register = new DeleteService();
        register.setVisible(true);
    }//GEN-LAST:event_delete_serv_buttonActionPerformed

    private void list_serv_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_serv_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_serv_buttonMouseEntered

    private void list_serv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_serv_buttonActionPerformed
        dispose();
        
        ListService ser = new ListService();
        ser.setVisible(true);
    }//GEN-LAST:event_list_serv_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_serv_button;
    private javax.swing.JButton delete_serv_button;
    private javax.swing.JTextField input_hour;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_price;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton list_serv_button;
    private javax.swing.JButton register_serv_button;
    // End of variables declaration//GEN-END:variables
}
