/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import model.Animal;
import models.dao.AnimalDao;
import models.dao.DaoFactory;

/**
 *
 * @author Vitor Manoel
 */
public class RegisterAnimal extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAnimal
     */
    public RegisterAnimal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        input_id = new javax.swing.JTextField();
        input_owner = new javax.swing.JTextField();
        input_especies = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        alter_pet_button = new javax.swing.JButton();
        list_pet_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator2.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 30));

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 300, 30));

        jSeparator4.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator4.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 300, 30));

        jSeparator1.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator1.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR ANIMAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 155, 52));
        jLabel5.setText("Especie:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 155, 52));
        jLabel4.setText("[CPF] Dono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 155, 52));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 155, 52));
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 30));

        input_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_name.setForeground(new java.awt.Color(209, 155, 52));
        input_name.setBorder(null);
        input_name.setCaretColor(new java.awt.Color(209, 155, 52));
        input_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_name.setInheritsPopupMenu(true);
        input_name.setName(""); // NOI18N
        input_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        jPanel1.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, 30));

        input_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_id.setForeground(new java.awt.Color(209, 155, 52));
        input_id.setBorder(null);
        input_id.setCaretColor(new java.awt.Color(209, 155, 52));
        input_id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_id.setInheritsPopupMenu(true);
        input_id.setName(""); // NOI18N
        input_id.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });
        jPanel1.add(input_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 250, 30));

        input_owner.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_owner.setForeground(new java.awt.Color(209, 155, 52));
        input_owner.setBorder(null);
        input_owner.setCaretColor(new java.awt.Color(209, 155, 52));
        input_owner.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_owner.setInheritsPopupMenu(true);
        input_owner.setName(""); // NOI18N
        input_owner.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_ownerActionPerformed(evt);
            }
        });
        jPanel1.add(input_owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, 30));

        input_especies.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_especies.setForeground(new java.awt.Color(209, 155, 52));
        input_especies.setBorder(null);
        input_especies.setCaretColor(new java.awt.Color(209, 155, 52));
        input_especies.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_especies.setInheritsPopupMenu(true);
        input_especies.setName(""); // NOI18N
        input_especies.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_especies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_especiesActionPerformed(evt);
            }
        });
        jPanel1.add(input_especies, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 200, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 110, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 40));

        alter_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_pet_button.setBorder(null);
        alter_pet_button.setBorderPainted(false);
        alter_pet_button.setContentAreaFilled(false);
        alter_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_pet_button.setFocusPainted(false);
        alter_pet_button.setFocusable(false);
        alter_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_pet_buttonMouseEntered(evt);
            }
        });
        alter_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_pet_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 120, 40));

        list_pet_button.setBackground(new java.awt.Color(254, 232, 231));
        list_pet_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_pet_button.setBorder(null);
        list_pet_button.setBorderPainted(false);
        list_pet_button.setContentAreaFilled(false);
        list_pet_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_pet_button.setFocusPainted(false);
        list_pet_button.setFocusable(false);
        list_pet_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_pet_buttonMouseEntered(evt);
            }
        });
        list_pet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_pet_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(list_pet_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 120, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed

    }//GEN-LAST:event_input_idActionPerformed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_especiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_especiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_especiesActionPerformed

    private void input_ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_ownerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AnimalDao animalDao = DaoFactory.createAnimalDao();
        Animal animal = new Animal();
        animal.setName(input_name.getText());
        animal.setId(Integer.parseInt(input_id.getText()));
        animal.setOwner(Integer.parseInt(input_owner.getText()));
        animal.setSpecies(input_especies.getText());
        
        animalDao.insert(animal);
        
        JOptionPane.showMessageDialog(null, "Animal cadastrado com sucesso!", "", 1);
        
        input_name.setText("");
        input_owner.setText("");
        input_id.setText("");
        input_especies.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        
        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alter_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_pet_buttonMouseEntered

    private void alter_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_pet_buttonActionPerformed
        dispose();

        AlterAnimal alter = new AlterAnimal();
        alter.setVisible(true);
    }//GEN-LAST:event_alter_pet_buttonActionPerformed

    private void list_pet_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_pet_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_pet_buttonMouseEntered

    private void list_pet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_pet_buttonActionPerformed
        dispose();

        ListAnimals list = new ListAnimals();
        list.setVisible(true);
    }//GEN-LAST:event_list_pet_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_pet_button;
    private javax.swing.JTextField input_especies;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_owner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton list_pet_button;
    // End of variables declaration//GEN-END:variables
}
