/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Products;
import models.dao.DaoFactory;
import models.dao.ProductsDao;

/**
 *
 * @author Vitor Manoel
 */
public class RegisterProd extends javax.swing.JFrame {
    
    Products product = new Products();
    ProductsDao productsDao = DaoFactory.createProductDao();
    
    /**
     * Creates new form RegisterProd
     */
    public RegisterProd() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        input_cat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        input_amaount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        alter_prod_button = new javax.swing.JButton();
        delete_prod_button = new javax.swing.JButton();
        list_prod_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator2.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 20));

        jSeparator3.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator3.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 280, 20));

        jSeparator4.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator4.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, 20));

        jSeparator1.setBackground(new java.awt.Color(209, 155, 52));
        jSeparator1.setForeground(new java.awt.Color(209, 155, 52));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 20));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-menu.png"))); // NOI18N
        jButton10.setToolTipText("");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 155, 52));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CADASTRAR PRODUTOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 155, 52));
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, 30));

        input_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_name.setForeground(new java.awt.Color(209, 155, 52));
        input_name.setBorder(null);
        input_name.setCaretColor(new java.awt.Color(209, 155, 52));
        input_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_name.setInheritsPopupMenu(true);
        input_name.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_name.setName(""); // NOI18N
        input_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        jPanel1.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 155, 52));
        jLabel2.setText("Categoria:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        input_cat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_cat.setForeground(new java.awt.Color(209, 155, 52));
        input_cat.setBorder(null);
        input_cat.setCaretColor(new java.awt.Color(209, 155, 52));
        input_cat.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_cat.setInheritsPopupMenu(true);
        input_cat.setMargin(new java.awt.Insets(2, 85, 2, 2));
        input_cat.setName(""); // NOI18N
        input_cat.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_catActionPerformed(evt);
            }
        });
        jPanel1.add(input_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 155, 52));
        jLabel3.setText("Quantidade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        input_amaount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_amaount.setForeground(new java.awt.Color(209, 155, 52));
        input_amaount.setBorder(null);
        input_amaount.setCaretColor(new java.awt.Color(209, 155, 52));
        input_amaount.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_amaount.setInheritsPopupMenu(true);
        input_amaount.setMargin(new java.awt.Insets(2, 100, 2, 2));
        input_amaount.setName(""); // NOI18N
        input_amaount.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_amaount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_amaountActionPerformed(evt);
            }
        });
        jPanel1.add(input_amaount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 155, 52));
        jLabel4.setText("Preço:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 30));

        input_price.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        input_price.setForeground(new java.awt.Color(209, 155, 52));
        input_price.setBorder(null);
        input_price.setCaretColor(new java.awt.Color(209, 155, 52));
        input_price.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        input_price.setInheritsPopupMenu(true);
        input_price.setMargin(new java.awt.Insets(2, 60, 2, 2));
        input_price.setName(""); // NOI18N
        input_price.setSelectionColor(new java.awt.Color(255, 255, 255));
        input_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_priceActionPerformed(evt);
            }
        });
        jPanel1.add(input_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 220, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottom-cadastrar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, 40));

        alter_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        alter_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-alterar.png"))); // NOI18N
        alter_prod_button.setBorder(null);
        alter_prod_button.setBorderPainted(false);
        alter_prod_button.setContentAreaFilled(false);
        alter_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alter_prod_button.setFocusPainted(false);
        alter_prod_button.setFocusable(false);
        alter_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alter_prod_buttonMouseEntered(evt);
            }
        });
        alter_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(alter_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 120, 40));

        delete_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        delete_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-excluir.png"))); // NOI18N
        delete_prod_button.setBorder(null);
        delete_prod_button.setBorderPainted(false);
        delete_prod_button.setContentAreaFilled(false);
        delete_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_prod_button.setFocusPainted(false);
        delete_prod_button.setFocusable(false);
        delete_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_prod_buttonMouseEntered(evt);
            }
        });
        delete_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(delete_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, 40));

        list_prod_button.setBackground(new java.awt.Color(254, 232, 231));
        list_prod_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buttons/bottom-registros.png"))); // NOI18N
        list_prod_button.setBorder(null);
        list_prod_button.setBorderPainted(false);
        list_prod_button.setContentAreaFilled(false);
        list_prod_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_prod_button.setFocusPainted(false);
        list_prod_button.setFocusable(false);
        list_prod_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                list_prod_buttonMouseEntered(evt);
            }
        });
        list_prod_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_prod_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(list_prod_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/border/Sem_título-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_catActionPerformed

    private void input_amaountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_amaountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_amaountActionPerformed

    private void input_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_priceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            product.setName(input_name.getText());
            product.setcategory(input_cat.getText());
            product.setamount(Integer.parseInt(input_amaount.getText()));
            product.setPrice(Float.parseFloat(input_price.getText()));
            product.setCnpj(999888777);

            productsDao.insert(product);
            
            JOptionPane.showMessageDialog(null, "Produto cadastrado!", "", 1);
             
            input_name.setText("");
            input_cat.setText("");
            input_amaount.setText("");
            input_price.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar produto.", "ERRO", 0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();

        EmployeeScreen employee = new EmployeeScreen();
        employee.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alter_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alter_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alter_prod_buttonMouseEntered

    private void alter_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter_prod_buttonActionPerformed
        dispose();

        AlterProducts register = new AlterProducts();
        register.setVisible(true);
    }//GEN-LAST:event_alter_prod_buttonActionPerformed

    private void delete_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_prod_buttonMouseEntered

    private void delete_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_prod_buttonActionPerformed
        dispose();

        DeleteProduct register = new DeleteProduct();
        register.setVisible(true);
    }//GEN-LAST:event_delete_prod_buttonActionPerformed

    private void list_prod_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_prod_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_list_prod_buttonMouseEntered

    private void list_prod_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_prod_buttonActionPerformed
        dispose();
        
        ListProducts pro = new ListProducts();
        pro.setVisible(true);
    }//GEN-LAST:event_list_prod_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alter_prod_button;
    private javax.swing.JButton delete_prod_button;
    private javax.swing.JTextField input_amaount;
    private javax.swing.JTextField input_cat;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton list_prod_button;
    // End of variables declaration//GEN-END:variables
}
