/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

/**
 *
 * @author Vitor Manoel
 */
public class TelaClinica extends javax.swing.JFrame {

    /**
     * Creates new form TelaClinica
     */
    public TelaClinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Menu_bar = new javax.swing.JMenuBar();
        Menu_bar_text = new javax.swing.JMenu();
        Op_menu_consultas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Op_menu_pets = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Op_menu_prod = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Op_menu_serv = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Op_menu_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(770, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        Menu_bar_text.setText("Menu");
        Menu_bar_text.setFocusable(false);
        Menu_bar_text.setMargin(new java.awt.Insets(5, 5, 0, 5));
        Menu_bar_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_bar_textActionPerformed(evt);
            }
        });

        Op_menu_consultas.setText("Consultas");
        Menu_bar_text.add(Op_menu_consultas);
        Menu_bar_text.add(jSeparator1);

        Op_menu_pets.setText("Meus Pets");
        Menu_bar_text.add(Op_menu_pets);
        Menu_bar_text.add(jSeparator2);

        Op_menu_prod.setText("Produtos");
        Menu_bar_text.add(Op_menu_prod);
        Menu_bar_text.add(jSeparator3);

        Op_menu_serv.setText("Serviços");
        Op_menu_serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op_menu_servActionPerformed(evt);
            }
        });
        Menu_bar_text.add(Op_menu_serv);
        Menu_bar_text.add(jSeparator4);

        Op_menu_sair.setText("Sair");
        Op_menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op_menu_sairActionPerformed(evt);
            }
        });
        Menu_bar_text.add(Op_menu_sair);

        Menu_bar.add(Menu_bar_text);

        setJMenuBar(Menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Op_menu_servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op_menu_servActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Op_menu_servActionPerformed

    private void Op_menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op_menu_sairActionPerformed
        dispose();
        PrimeiraTela home = new PrimeiraTela();
        home.setVisible(true);
    }//GEN-LAST:event_Op_menu_sairActionPerformed

    private void Menu_bar_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_bar_textActionPerformed

    }//GEN-LAST:event_Menu_bar_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu_bar;
    private javax.swing.JMenu Menu_bar_text;
    private javax.swing.JMenuItem Op_menu_consultas;
    private javax.swing.JMenuItem Op_menu_pets;
    private javax.swing.JMenuItem Op_menu_prod;
    private javax.swing.JMenuItem Op_menu_sair;
    private javax.swing.JMenuItem Op_menu_serv;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
